{
 "title": "Spa",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spanet_water_temperature or spanet_water_temp)"
    },
    {
     "expr": "sum(spanet_target_temperature or spanet_target_temp) + 1"
    }
   ]
  },
  {
   "title": "Heater",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spanet_heating" }
   ]
  },
  {
   "title": "Sanitising",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spanet_sanitising" }
   ]
  },
  {
   "title": "Cleaning",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spanet_cleaning" }
   ]
  },
  {
   "title": "Sleeping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spanet_sleeping" }
   ]
  },
  {
   "title": "Lights",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spanet_lights_active" }
   ]
  },
  {
   "title": "Jets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spanet_pump_active{pump=\"2\"}"
    }
   ]
  },
  {
   "title": "Circulation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spanet_pump_active{pump=\"4\"}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Water Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(spanet_water_temperature or spanet_water_temp) by (spa_name)",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(spanet_target_temperature or spanet_target_temp) by (spa_name)",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Heating",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "spanet_heating" }
   ]
  },
  { "title": "Pumps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Pumps Active",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "spanet_pump_active", "legendFormat": "Pump {{ pump }}" }
   ]
  },
  {
   "title": "Lights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      { "expr": "spanet_lights_active" }
     ]
    },
    {
     "title": "Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "spanet_lights_mode", "legendFormat": "Mode" }
     ]
    },
    {
     "title": "Lights Brightness",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "spanet_lights_brightness", "legendFormat": "Brightness" }
     ]
    },
    {
     "title": "Lights Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "spanet_lights_speed", "legendFormat": "Speed" }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sanitising",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      { "expr": "spanet_sanitising" }
     ]
    },
    {
     "title": "Cleaning",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      { "expr": "spanet_cleaning" }
     ]
    },
    {
     "title": "Sleeping",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      { "expr": "spanet_sleeping" }
     ]
    },
    {
     "title": "Panel Lock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "spanet_locked" }
     ]
    }
   ]
  },
  {
   "title": "Blower",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blower Mode",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "spanet_blower_mode", "legendFormat": "Mode" }
     ]
    },
    {
     "title": "Blower Speed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "spanet_blower_speed", "legendFormat": "Speed" }
     ]
    }
   ]
  }
 ]
}